# PowerShell script to generate a Win32 resource script (.rc) file
# This script scans the Icons directory and creates a .rc file that references all .ico files

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$iconsDir = Join-Path $projectRoot "Icons"
$outputRc = Join-Path $projectRoot "WindowsIcons.rc"
$outputHeader = Join-Path $projectRoot "resource.h"

Write-Host "Scanning for .ico files in: $iconsDir"

# Get all .ico files recursively
$iconFiles = Get-ChildItem -Path $iconsDir -Filter "*.ico" -Recurse | Sort-Object FullName

if ($iconFiles.Count -eq 0) {
    Write-Error "No .ico files found in $iconsDir"
    exit 1
}

Write-Host "Found $($iconFiles.Count) icon files"

# Generate resource.h header file
$headerContent = @"
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ compatible resource header
// Generated by GenerateResourceScript.ps1

"@

$resourceId = 101
foreach ($iconFile in $iconFiles) {
    $relativePath = $iconFile.FullName.Substring($projectRoot.Length + 1).Replace('\', '_').Replace('/', '_').Replace('.', '_').Replace(' ', '_').Replace('-', '_').ToUpper()
    $resourceName = "IDI_$relativePath"
    $headerContent += "#define $resourceName $resourceId`r`n"
    $resourceId++
}

$headerContent += "`r`n// Next default values for new objects`r`n"
$headerContent += "#ifdef APSTUDIO_INVOKED`r`n"
$headerContent += "#ifndef APSTUDIO_READONLY_SYMBOLS`r`n"
$headerContent += "#define _APS_NEXT_RESOURCE_VALUE $resourceId`r`n"
$headerContent += "#define _APS_NEXT_COMMAND_VALUE 40001`r`n"
$headerContent += "#define _APS_NEXT_CONTROL_VALUE 1000`r`n"
$headerContent += "#define _APS_NEXT_SYMED_VALUE 101`r`n"
$headerContent += "#endif`r`n"
$headerContent += "#endif`r`n"

Write-Host "Writing resource header: $outputHeader"
[System.IO.File]::WriteAllText($outputHeader, $headerContent)

# Generate .rc resource script
$rcContent = @"
// Microsoft Visual C++ compatible resource script
// Generated by GenerateResourceScript.ps1
// This file defines Win32 ICON resources that are accessible by Windows Explorer's icon picker

#include "resource.h"
#include <windows.h>

/////////////////////////////////////////////////////////////////////////////
// English (United States) resources

LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US

/////////////////////////////////////////////////////////////////////////////
// Icon resources with type RT_GROUP_ICON
//

"@

$resourceId = 101
foreach ($iconFile in $iconFiles) {
    # Get relative path from project root
    $relativePath = $iconFile.FullName.Substring($projectRoot.Length + 1).Replace('\', '/')
    $resourceName = $relativePath.Replace('\', '_').Replace('/', '_').Replace('.', '_').Replace(' ', '_').Replace('-', '_').ToUpper()

    # Escape backslashes in path for RC file
    $rcPath = $relativePath.Replace('\', '\\')

    $rcContent += "IDI_$resourceName ICON `"$rcPath`"`r`n"
    $resourceId++
}

Write-Host "Writing resource script: $outputRc"
[System.IO.File]::WriteAllText($outputRc, $rcContent)

Write-Host "Successfully generated resource files!"
Write-Host "  - Resource header: $outputHeader"
Write-Host "  - Resource script: $outputRc"
Write-Host "  - Total icons: $($iconFiles.Count)"
