using System;
using System.IO;
using System.Linq;
using System.Text;

namespace ResourceScriptGenerator;

class Program
{
    static int Main(string[] args)
    {
        try
        {
            // Determine the repository root - navigate up from ResourceScriptGenerator directory
            var projectRoot = Path.GetDirectoryName(AppContext.BaseDirectory);
            if (projectRoot == null)
            {
                Console.Error.WriteLine("ERROR: Could not determine project root directory");
                return 1;
            }

            // Navigate up from ResourceScriptGenerator/bin/Debug/net8.0 to repository root
            projectRoot = Path.GetFullPath(Path.Combine(projectRoot, "..", "..", "..", ".."));

            var iconsDir = Path.Combine(projectRoot, "Icons");
            var outputRc = Path.Combine(projectRoot, "WindowsIcons.rc");
            var outputHeader = Path.Combine(projectRoot, "resource.h");

            Console.WriteLine($"Scanning for .ico files in: {iconsDir}");

            if (!Directory.Exists(iconsDir))
            {
                Console.Error.WriteLine($"ERROR: Icons directory not found: {iconsDir}");
                return 1;
            }

            // Get all .ico files recursively
            var iconFiles = Directory.GetFiles(iconsDir, "*.ico", SearchOption.AllDirectories)
                .OrderBy(f => f)
                .ToArray();

            if (iconFiles.Length == 0)
            {
                Console.Error.WriteLine($"ERROR: No .ico files found in {iconsDir}");
                return 1;
            }

            Console.WriteLine($"Found {iconFiles.Length} icon files");

            // Generate resource.h header file
            var headerContent = new StringBuilder();
            headerContent.AppendLine("//{{NO_DEPENDENCIES}}");
            headerContent.AppendLine("// Microsoft Visual C++ compatible resource header");
            headerContent.AppendLine("// Generated by ResourceScriptGenerator");
            headerContent.AppendLine();

            var resourceId = 101;
            foreach (var iconFile in iconFiles)
            {
                var relativePath = iconFile.Substring(projectRoot.Length + 1)
                    .Replace('\\', '_')
                    .Replace('/', '_')
                    .Replace('.', '_')
                    .Replace(' ', '_')
                    .Replace('-', '_')
                    .ToUpper();
                var resourceName = $"IDI_{relativePath}";
                headerContent.AppendLine($"#define {resourceName} {resourceId}");
                resourceId++;
            }

            headerContent.AppendLine();
            headerContent.AppendLine("// Next default values for new objects");
            headerContent.AppendLine("#ifdef APSTUDIO_INVOKED");
            headerContent.AppendLine("#ifndef APSTUDIO_READONLY_SYMBOLS");
            headerContent.AppendLine($"#define _APS_NEXT_RESOURCE_VALUE {resourceId}");
            headerContent.AppendLine("#define _APS_NEXT_COMMAND_VALUE 40001");
            headerContent.AppendLine("#define _APS_NEXT_CONTROL_VALUE 1000");
            headerContent.AppendLine("#define _APS_NEXT_SYMED_VALUE 101");
            headerContent.AppendLine("#endif");
            headerContent.AppendLine("#endif");

            Console.WriteLine($"Writing resource header: {outputHeader}");
            File.WriteAllText(outputHeader, headerContent.ToString());

            // Generate .rc resource script
            var rcContent = new StringBuilder();
            rcContent.AppendLine("// Microsoft Visual C++ compatible resource script");
            rcContent.AppendLine("// Generated by ResourceScriptGenerator");
            rcContent.AppendLine("// This file defines Win32 ICON resources that are accessible by Windows Explorer's icon picker");
            rcContent.AppendLine();
            rcContent.AppendLine("#include \"resource.h\"");
            rcContent.AppendLine("#include <windows.h>");
            rcContent.AppendLine();
            rcContent.AppendLine("/////////////////////////////////////////////////////////////////////////////");
            rcContent.AppendLine("// English (United States) resources");
            rcContent.AppendLine();
            rcContent.AppendLine("LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US");
            rcContent.AppendLine();
            rcContent.AppendLine("/////////////////////////////////////////////////////////////////////////////");
            rcContent.AppendLine("// Icon resources with type RT_GROUP_ICON");
            rcContent.AppendLine("//");
            rcContent.AppendLine();

            resourceId = 101;
            foreach (var iconFile in iconFiles)
            {
                // Get relative path from project root
                var relativePath = iconFile.Substring(projectRoot.Length + 1).Replace('\\', '/');
                var resourceName = relativePath
                    .Replace('\\', '_')
                    .Replace('/', '_')
                    .Replace('.', '_')
                    .Replace(' ', '_')
                    .Replace('-', '_')
                    .ToUpper();

                // Escape backslashes in path for RC file
                var rcPath = relativePath.Replace("\\", "\\\\");

                rcContent.AppendLine($"IDI_{resourceName} ICON \"{rcPath}\"");
                resourceId++;
            }

            Console.WriteLine($"Writing resource script: {outputRc}");
            File.WriteAllText(outputRc, rcContent.ToString());

            Console.WriteLine("Successfully generated resource files!");
            Console.WriteLine($"  - Resource header: {outputHeader}");
            Console.WriteLine($"  - Resource script: {outputRc}");
            Console.WriteLine($"  - Total icons: {iconFiles.Length}");

            return 0;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"ERROR: {ex.Message}");
            return 1;
        }
    }
}
